Repository FRONTENDBOOTCAMP-13th/JS-11-nu11, pull requests merged in 2025-05, with the labels that each got.

#15 🎉 init: 이미지 폴더 추가, 폰트 추가 및 설정
  index.html
  public/assets/fonts/suit/SUIT-Bold.otf
  public/assets/fonts/suit/SUIT-Bold.ttf
  public/assets/fonts/suit/SUIT-Bold.woff2
  public/assets/fonts/suit/SUIT-ExtraBold.otf
  public/assets/fonts/suit/SUIT-ExtraBold.ttf
  public/assets/fonts/suit/SUIT-ExtraBold.woff2
  public/assets/fonts/suit/SUIT-ExtraLight.otf
  public/assets/fonts/suit/SUIT-ExtraLight.ttf
  public/assets/fonts/suit/SUIT-ExtraLight.woff2
  public/assets/fonts/suit/SUIT-Heavy.otf
  public/assets/fonts/suit/SUIT-Heavy.ttf
  public/assets/fonts/suit/SUIT-Heavy.woff2
  public/assets/fonts/suit/SUIT-Light.otf
  public/assets/fonts/suit/SUIT-Light.ttf
  public/assets/fonts/suit/SUIT-Light.woff2
  public/assets/fonts/suit/SUIT-Medium.otf
  public/assets/fonts/suit/SUIT-Medium.ttf
  public/assets/fonts/suit/SUIT-Medium.woff2
  public/assets/fonts/suit/SUIT-Regular.otf
  public/assets/fonts/suit/SUIT-Regular.ttf
  public/assets/fonts/suit/SUIT-Regular.woff2
  public/assets/fonts/suit/SUIT-SemiBold.otf
  public/assets/fonts/suit/SUIT-SemiBold.ttf
  public/assets/fonts/suit/SUIT-SemiBold.woff2
  public/assets/fonts/suit/SUIT-Thin.otf
  public/assets/fonts/suit/SUIT-Thin.ttf
  public/assets/fonts/suit/SUIT-Thin.woff2
  public/assets/fonts/suit/suit.css
  src/assets/images/intro.png
  src/main.ts
  src/style.css
  test-psh.js
  test-sugon.js
  test-wonsik.js
  test-yong.js
Labels: 🎉 초기 셋팅

#17 ✨ feat: 운동하기 기능 1차로 추가
  src/pages/health/Group 18.png
  src/pages/health/health.ts
  src/pages/health/index.html
Labels: ✨ 새로운 기능 추가

#18 청소기능#11
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/img/character.svg
  src/pages/cleaning/img/redbull.svg
  src/pages/cleaning/index.html
  src/pages/cleaning/style.css
Labels: ✨ 새로운 기능 추가

#20 Feature/study-start.html
  src/pages/study/assets/white-board.png
  src/pages/study/index.html
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
  src/pages/study/study.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#22 Feature/study.html
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#37 🚚 rename: 퀴즈게임 메인화면, 게임 화면 이미지 추가 및 이동
  src/assets/images/study - intro.png
  src/assets/images/white-board.png
Labels: 🚚 파일명 수정/이동

#38 🚚 rename: health 페이지 이미지 추가 , 인덱스 파일 경로 수정
  src/assets/images/celebrate.png
  src/assets/images/health.png
  src/assets/images/spacebar2d.png
  src/assets/images/spacebar3d.png
  src/pages/health/index.html
Labels: 🚚 파일명 수정/이동

#44 Cleaning kyo
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/index.html
Labels: ✨ 새로운 기능 추가

#43 25-feat-intro-hsg
  src/assets/images/study - intro.png
  src/assets/images/study_intro.svg
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: 🚚 파일명 수정/이동, ✨ 새로운 기능 추가, 🔥 파일 삭제, 🎨 스타일

#41 🎨 style: 결과 화면 스타일 추가
  src/pages/health/index.html
Labels: 🎨 스타일

#45 결과 페이지 : 성공과 실패
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/index.html
  src/pages/cleaning/style.css
Labels: ✨ 새로운 기능 추가

#46 ✨ feat: 게임 시작할때마다 랜덤한 문제 출력
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#47 ✨ feat: 문제 5개 출력, OX 버튼 누르면 다음 문제로 넘어가도록 구현 완료
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가

#50 🔥 remove: 사용하지 않는 폴더들 정리
  src/counter.ts
  src/main.ts
  src/pages/eat/eat.ts
  src/pages/eat/index.html
  src/pages/eat/style.css
  src/pages/main/main.js
  src/pages/sleep/index.html
  src/pages/sleep/sleep.ts
  src/pages/sleep/style.css
Labels: ⚰️ 코드 정리, 🔥 파일 삭제

#53 ✨ feat: 유저가 고른 답에 따른 정답 여부 판단하여 정/오답 처리 및 상황판에 출력 기능 구현
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가, ♻️ 코드 리팩토링, 🎨 스타일

#54 ✨ feat: 되돌아가기 버튼 클릭 시 메인화면으로 돌아가는 기능 구현
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#55 ✨ feat: 엔딩페이지 전체 정답, 전체 오답 처리 기능 구현
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
  src/pages/study/style.css
Labels: ✨ 새로운 기능 추가, 🧪 테스트, 🎨 스타일

#56 feat: 5문제중 일부만 맞췄을 때 해당 페이지 넘어가도록 기능 구현
  src/pages/study/study-start.html
  src/pages/study/study-start.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#57 51 style Change kyo
  src/assets/failsound.mp3
  src/assets/images/cleaning_intro.svg
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/index.html
Labels: ✨ 새로운 기능 추가, ♻️ 코드 리팩토링, 🎨 스타일

#58 ♻️ refactor: 운동하기 - 반응형 스타일로 수정
  src/assets/images/health_intro.svg
  src/assets/images/health_play.png
  src/assets/images/health_spacebar2d.png
  src/assets/images/health_spacebar3d.png
  src/pages/health/health.ts
  src/pages/health/index.html
  src/pages/health/style.css
Labels: 🚚 파일명 수정/이동, ♻️ 코드 리팩토링, 🎨 스타일

#59 ✨ feat: 로컬스토리지로 exPoint 저장 기능 구현
  src/pages/study/study-start.ts
Labels: ⚰️ 코드 정리, ✨ 새로운 기능 추가

#65 🚚 rename: 파일명 수정/이동
  src/assets/images/cleaning_character.svg
  src/assets/images/cleaning_redbull.svg
  src/assets/images/health_celebrate.png
  src/assets/images/main_dying.svg
  src/assets/images/study_white-board.png
Labels: 🚚 파일명 수정/이동

#66 🚚 rename: 파일명 수정
  src/pages/study/index.html
  src/pages/study/study.ts
Labels: 🚚 파일명 수정/이동

#67 ✨ feat: 각 엔딩 페이지별 게임 메인으로 되돌아갈 수 있도록 버튼 이벤트 수정
  src/pages/study/index.html
  src/pages/study/study.ts
Labels: ✨ 새로운 기능 추가, 🎨 스타일

#68 ✨ feat: ending페이지, dying페이지 구현
  src/assets/images/food_hamburger.png
  src/assets/images/food_result.svg
  src/pages/main/index.html
  src/pages/main/main.js
  src/style.css
Labels: ✨ 새로운 기능 추가

#75 ♻️ refactor: 전반적인 CSS작업 및 코드리펙토링
  src/main.js
  src/pages/cleaning/cleaning.js
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/index.html
  src/pages/cleaning/style.css
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/health/index.html
  src/pages/health/style.css
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/pages/main/style.css
  src/pages/study/index.html
  src/pages/study/study.js
  src/pages/study/study.ts
  src/pages/study/style.css
  src/style.css
  tsconfig.json
  vite.config.js
Labels: 🐞 버그 수정, ⚰️ 코드 정리, ♻️ 코드 리팩토링, 🎨 스타일

#76 feat: 대표 페이지 UI 및 기능 작업
  index.html
  src/main.ts
Labels: 🎨 스타일

#78 🚚 rename: 대표 인덱스 페이지 외부 모듈 파일 수정
  index.html
  src/assets/js/introduce.ts
  src/main.ts
Labels: 🚚 파일명 수정/이동, ♻️ 코드 리팩토링

#80 🌐 deploy: 2차 배포
  src/assets/js/introduce.js
Labels: 🌐 배포

#81 [배포] 2차 배포
  index.html
  src/assets/js/introduce.js
  src/assets/js/introduce.ts
  src/main.js
  src/pages/cleaning/cleaning.js
  src/pages/cleaning/cleaning.ts
  src/pages/cleaning/index.html
  src/pages/cleaning/style.css
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/health/index.html
  src/pages/health/style.css
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/pages/main/style.css
  src/pages/study/index.html
  src/pages/study/study.js
  src/pages/study/study.ts
  src/pages/study/style.css
  src/style.css
  tsconfig.json
  vite.config.js
Labels: 🌐 배포

#82 🧪 test: main내용 병합
  README.md
Labels: 🧪 테스트, 🌐 배포

#83 메인으로 병합
  README.md
Labels: 🧪 테스트

#85 ✨ feat: 3차 배포전 이슈 처리사항 및 엔딩페이지 구현, 음성파일 적용
  .vscode/settings.json
  public/assets/images/ending.jpg
  public/assets/images/main_joongsu.svg
  public/assets/images/sleep_gosu.svg
  public/assets/images/sleep_joongsu.svg
  public/assets/sounds/cleaning_fail.mp3
  public/assets/sounds/eat_drink.mp3
  public/assets/sounds/eat_food.m4a
  public/assets/sounds/health_fail.mp3
  public/assets/sounds/sleep.m4a
  public/assets/sounds/sleep_long.mp3
  public/assets/sounds/study_fail.mp3
  public/assets/sounds/success.mp3
  src/pages/cleaning/cleaning.js
  src/pages/cleaning/cleaning.ts
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/pages/study/index.html
  src/pages/study/study.js
  src/pages/study/study.ts
  src/style.css
Labels: ⚰️ 코드 정리, ✨ 새로운 기능 추가, 🚧 진행중인 작업, ♻️ 코드 리팩토링, 🎨 스타일

#87 🧪 test: 배포 전 빌드 테스트
  README.md
Labels: 🧪 테스트

#88 [배포] 3차 배포 진행
  .vscode/settings.json
  README.md
  public/assets/images/ending.jpg
  public/assets/images/main_joongsu.svg
  public/assets/images/sleep_gosu.svg
  public/assets/images/sleep_joongsu.svg
  public/assets/sounds/cleaning_fail.mp3
  public/assets/sounds/eat_drink.mp3
  public/assets/sounds/eat_food.m4a
  public/assets/sounds/health_fail.mp3
  public/assets/sounds/sleep.m4a
  public/assets/sounds/sleep_long.mp3
  public/assets/sounds/study_fail.mp3
  public/assets/sounds/success.mp3
  src/pages/cleaning/cleaning.js
  src/pages/cleaning/cleaning.ts
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/pages/study/index.html
  src/pages/study/study.js
  src/pages/study/study.ts
  src/style.css
Labels: 🌐 배포

#91 📝 docs: README 파일 수정
  README.md
Labels: 📝 문서 추가/수정

#92 🐞 fix: 3차 배포관련 버그 및 이슈 수정
  src/pages/cleaning/index.html
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/style.css
Labels: 🐞 버그 수정

#93 [배포] 4차 배포
  README.md
  src/pages/cleaning/index.html
  src/pages/health/health.js
  src/pages/health/health.ts
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/main.ts
  src/style.css
Labels: 🌐 배포

#96 📝 docs: README 내용 2차 수정
  README.md
Labels: 📝 문서 추가/수정

#98 🐞 fix: 4차 배포 관련 버그 수정
  src/pages/main/main.js
  src/pages/main/main.ts
Labels: 🐞 버그 수정

#99 [배포] 5차 배포
  README.md
  src/pages/main/main.js
  src/pages/main/main.ts
Labels: 🌐 배포
